spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  mail:
    host: smtp.qq.com
    username: 2206186360@qq.com
    password: qqwimavulkehebef
    port: 465
    properties:
      from: 2206186360@qq.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    data:
        redis:
          database: 0
          host: localhost
          port: 6379
